name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  semver-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
      - name: semver & changelog
        run: |
          date > generated.txt
          git config user.name github-svc
          git config user.email github-svc@ohpen.com
          node ./scripts/generate-version-and-release-notes.js

  tfm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.10.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          template: # Documentation<br><br><!--- BEGIN\_TF\_DOCS ---><br><!--- END\_TF\_DOCS ---><br>
